name: app_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.0.0


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2
  get_it: ^7.6.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3

  # Location & Maps
  geolocator: ^10.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geoflutterfire_plus: ^0.0.3
  geocoding: ^2.1.0


  # Local Storage
  shared_preferences: ^2.2.2

  # Utils
  dartz: ^0.10.1
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

